import {
  featherArrowLeft,
  featherBarChart2,
  featherCheck,
  featherCheckCircle,
  featherChevronDown,
  featherChevronUp,
  featherEdit,
  featherFeather,
  featherGrid,
  featherLoader,
  featherLogIn,
  featherLogOut,
  featherMenu,
  featherMinus,
  featherPlus,
  featherSettings,
  featherTrash,
  featherUser,
  featherX,
  featherZap,
} from '@ng-icons/feather-icons';

const icons = {
  featherArrowLeft,
  featherBarChart2,
  featherCheck,
  featherCheckCircle,
  featherChevronDown,
  featherChevronUp,
  featherEdit,
  featherFeather,
  featherGrid,
  featherLoader,
  featherLogIn,
  featherLogOut,
  featherUser,
  featherMenu,
  featherMinus,
  featherPlus,
  featherSettings,
  featherTrash,
  featherX,
  featherZap,
};

enum Feather {
  ArrowLeft = 'featherArrowLeft',
  BarChart2 = 'featherBarChart2',
  Check = 'featherCheck',
  CheckCircle = 'featherCheckCircle',
  ChevronDown = 'featherChevronDown',
  ChevronUp = 'featherChevronUp',
  Edit = 'featherEdit',
  Feather = 'featherFeather',
  Grid = 'featherGrid',
  Loader = 'featherLoader',
  LogIn = 'featherLogIn',
  LogOut = 'featherLogOut',
  Menu = 'featherMenu',
  Plus = 'featherPlus',
  Minus = 'featherMinus',
  Settings = 'featherSettings',
  Trash = 'featherTrash',
  User = 'featherUser',
  X = 'featherX',
  Zap = 'featherZap',
}

export const NGIcons = {
  feather: Feather,
};
export default { ...icons };
